name: nordstream-leak
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - pooch
  - scipy
  - tqdm
  - pip
# fair2.1 needs to be pip-installed from a local repository. If you have this, edit the path below.
  - pip:
    - -e ../fair2.1-calibrate
